version: "3"
services:
  web:
    build: .
    image: datingapp
    ports:
      - "5000:5000"
    restart: always
    links:
      - mysql-db
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:5.7
    container_name: mysql-datingapp
    restart: always
    environment:
      MYSQL_USER: appuser
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: datingappmysql-db
    ports:
      - "3306:3306"
